install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt55base qt55declarative qt55location
script:
  - source /opt/qt54/bin/qt54-env.sh
  - qmake projects.pro
  - make
  - bash test.sh
