install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt54-beta
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt54base qt54declarative
script:
  - /opt/qt54/bin/qt54-env.sh
  - qmake projects.pro
  - make
